theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: angelrodes.github.io
permalink: /404.html
email: "contact@angelrodes.com"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
